// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// atm_pres
NumericVector atm_pres(NumericVector altitude_m);
RcppExport SEXP _physiology_atm_pres(SEXP altitude_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type altitude_m(altitude_mSEXP);
    rcpp_result_gen = Rcpp::wrap(atm_pres(altitude_m));
    return rcpp_result_gen;
END_RCPP
}
// atm_pres_frac
NumericVector atm_pres_frac(NumericVector altitude_m);
RcppExport SEXP _physiology_atm_pres_frac(SEXP altitude_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type altitude_m(altitude_mSEXP);
    rcpp_result_gen = Rcpp::wrap(atm_pres_frac(altitude_m));
    return rcpp_result_gen;
END_RCPP
}
