# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get mean atmospheric pressure at given altitude
#' @param altitude_m Altitude above mean sea level in meters
#' @return Pressure in pascals
#' @examples
#' atm_pres(-430.5) # Dead Sea
#' atm_pres(0)
#' atm_pres(3440) # Namche Bazaar
#' atm_pres(4260) # Dingboche
#' atm_pres(5364) # Everest Base Camp
#' atm_pres(6000) # Camp 1
#' atm_pres(6400) # Camp 2
#' atm_pres(7200) # Camp 3
#' atm_pres(7950) # Camp 4
#' atm_pres(8850) # Everest summit
#' atm_pres_frac(8850) # fraction of sea level pressure on Everest
#' @concept atmospheric pressure
#' @export
atm_pres <- function(altitude_m) {
    .Call(`_physiology_atm_pres`, altitude_m)
}

#' @describeIn atm_pres Get fraction of mean atomspheric pressure at sea level
#' @export
atm_pres_frac <- function(altitude_m) {
    .Call(`_physiology_atm_pres_frac`, altitude_m)
}

